app:
  app_name: "Voteme" # 应用名称
  port: 9090    # 服务启用端口

db:
  host: "47.92.151.211"     # host
  port: 13306          # port
  user: "root"        # user
  password: "123456"  # password
  dbname: "voteme"    # dbname
  max_idle_conn: 500    # 最大空闲连接数
  max_open_conn: 1000   # 最大连接数
  max_idle_time: 300  # 最大空闲时间

redis:
  rhost: "47.92.151.211"
  rport: 16379
  rdb: 0
  passwd: ''
  poolsize: 400
  min_idle_coons: 100

maxVotes: 100000 # 一个票据最大投票次数
ticketUpdateTime: 100s # 一个票据的失效时间
ticketLen: 10 # 票据最大长度
ticketCacheRefreshTime: 2s # 票数缓存刷新时间
votesCacheToDbTime: 2s # redis 中的投票数据，多久刷盘一次

goGc: 1000 # go程序gc步调